# Generated by Django 3.2.6 on 2021-12-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='게시글 아이디')),
                ('category', models.CharField(default='기본 게시판', max_length=128, verbose_name='카테고리')),
                ('title', models.CharField(max_length=32, null=True, verbose_name='게시글 제목')),
                ('contents', models.TextField(verbose_name='게시글 내용')),
                ('writer', models.CharField(max_length=32, verbose_name='작성자')),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
                'db_table': 'board',
            },
        ),
    ]
