# Generated by Django 3.2.6 on 2021-12-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='게시글 제목'),
        ),
    ]
